In [1]:
%load_ext autoreload
%autoreload 2


In [3]:
import sys
sys.path.insert(0,"/mnt/nvme/node02/pranav/AE24/chitVachana/cape")

In [5]:
from cape.align import alignEEG
reload_path= "/mnt/nvme/node02/pranav/AE24/chitVachana/cape/aligne/checkpoint/align/maeeg_afg_5_24_5.48.ckpt"

In [9]:
import torch
alignEEG.load_from_checkpoint(reload_path,map_location=torch.device('cpu') )

RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.

In [3]:
dummy ={'trainer_maeeg_pretrain_config': {'run_name': 'maeeg_512_enc768_dec256', 'lr': 0.0001, 'weight_decay': 0.07, 'num_epochs': 200, 'warmup_epochs': 10, 'batch_size': 60, 'num_workers': 2, 'clip_grad': 0.8, 'time_len': 640, 'hop_length': 128, 'data_path': '/mnt/nvme/node02/pranav/AE24/data/split_data', 'output_path': '/mnt/nvme/node02/pranav/AE24/chitVachana/cape', 'reload_path': '', 'resume_wandb': '', 'normalize_data': 2, 'seed': 2024}, 'trainer_maeeg_align_config': {'run_name': 'maeeg_align_freeze_gpt', 'lr': 0.001, 'weight_decay': 0.07, 'num_epochs': 100, 'warmup_epochs': 0, 'freeze': True, 'batch_size': 256, 'num_workers': 8, 'clip_grad': 0.8, 'data_path': '/mnt/nvme/node02/pranav/AE24/data/split_data', 'output_path': '/mnt/nvme/node02/pranav/AE24/chitVachana/cape/aligne', 'reload_path': '/mnt/nvme/node02/pranav/AE24/chitVachana/cape/aligne/checkpoint/maeeg_align_freeze_gpt_1data_16-04-2024-11-43.ckpt', 'resume_wandb': '', 'normalize_data': 2, 'subset': 0.5, 'seed': 2024, 'weight': 0.8}, 'trainer_ldm_config': {'run_name': 'ldm_finetune', 'lr': 0.001, 'weight_decay': 0.07, 'num_epochs': 100, 'warmup_epochs': 10, 'freeze': True, 'batch_size': 120, 'num_workers': 8, 'clip_grad': 0.8, 'data_path': '/mnt/nvme/node02/pranav/AE24/data/split_data', 'output_path': '/mnt/nvme/node02/pranav/AE24/chitVachana/ldm_models', 'reload_path': '', 'resume_wandb': '', 'normalize_data': 2, 'subset': 1, 'seed': 2024, 'weight': 0.8}, 'ldm_config': {'params': {'in_channels': 1, 't_steps': 1,
'img_depth': 1, 'num_tsteps': 1}}, 'lr': 0.001, 'weight_decay': 0.07, 'warmup_epochs': 0, 'freeze': True, 'clip_grad': 0.8, 'seed': 2024, 'weight': 0.8}



In [14]:
def p(warmup_epochs,**kwargs):
    print(warmup_epochs)

    
class testclass:
    def __init__(self,**kwargs):

        p(**kwargs)

In [ ]:
import audioldm2.latent_diffusion.modules.phoneme_encoder.text as text
from audioldm2.latent_diffusion.util import get_vits_phoneme_ids_no_padding
import re

def text2phoneme(data,language="nl"):
    return text._clean_text(re.sub(r'<.*?>', '', data), lng = language)

In [39]:
from cape.dataset import eeg_pretrain_dataset
from torch.utils.data import DataLoader
import torch
from tqdm import tqdm
dataset= eeg_pretrain_dataset( frame_length=640, hop_length=640)
dl =  DataLoader(dataset,batch_size=200)
sample =next(iter(dl))

In [60]:
#correlation
import numpy as np
x1=sample['eeg']

b,c,l=x1.shape
x2=sample['eeg']**2#*np.rand(b,c,l)
x3= np.random.rand(b*c,l)*20
x1 = x1.reshape((b*c,l))
x2 = x2.reshape((b*c,l))*np.random.rand(b*c,l)
corrs =np.zeros((b*c))
for i in range(b*c):
    corrs[i]=(np.corrcoef(x1[i,:],x2[i,:])[0,1])

In [ ]:
from cape.dataset import eeg_pretrain_dataset
import torch
from tqdm import tqdm
dataset= eeg_pretrain_dataset( frame_length":640, hop_length":640)

summ1":0
sqsum1":0
for data in tqdm(dataset):
    # Assuming data is of shape [batch_size, channels, height, width]
    data":data['eeg']
    summ1+":torch.sum(data,1)
    sqsum1 +": torch.sum(data**2,1)



In [ ]:
from cape.dataset import eeg_pretrain_dataset
import torch
from tqdm import tqdm
dataset= eeg_pretrain_dataset( frame_length=640, hop_length=640)

In [1]:
dataset.__getitem__(2)['eeg'].sum(1).shape

NameError: name 'dataset' is not defined

In [17]:
tl1 =(len(dataset)*640)
tl=tl1*64
mean1 = summ1 / tl1
std1 = ((sqsum1/tl1) - mean1 ** 2) ** 0.5

mean =summ/tl
std= ((sqsum/tl) - mean ** 2) ** 0.5
mean,std

(tensor(-2.8759e-06), tensor(6.5272))

In [26]:
data - k[:,None]

tensor([[ 0.4186, -4.1960, -2.9934,  ..., -5.3522, -7.0694, -3.4714],
        [-3.3748, -6.9157, -6.4160,  ..., -2.7544, -4.3028, -1.8144],
        [ 2.3882, -2.9068, -0.8884,  ..., -1.8801, -3.6027,  0.4009],
        ...,
        [-3.3323, -6.6796, -3.4051,  ...,  2.1607, -2.0779, -2.8805],
        [-5.3103, -6.0054, -5.6233,  ...,  2.5618,  0.6299, -1.8995],
        [-5.2485, -6.3649, -2.4378,  ..., -1.3232, -2.3433, -4.7357]])

# CAPE TEST

In [ ]:
from cape.train import *

from cape.config import config_dict

main(config_dict["maeeg-config"], **config_dict["trainer-config"])

    

In [26]:
1024/16,128/16

(64.0, 8.0)

In [70]:
#test code for maeeg
from torch import nn
from cape.dataset import eeg_pretrain_dataset
from torch.utils.data import DataLoader


WERE= eeg_pretrain_dataset(path='/mnt/nvme/node02/pranav/AE24/data/split_data',frame_length=640,hop_length=64)
test_dataloader = DataLoader(WERE, batch_size=6, num_workers=6, 
            shuffle=True, pin_memory=True)
test =next(iter(test_dataloader))['eeg'][:,None,...]

# patch_embed = Patch2DEmbed()
# patch_embed(test).shape,test.shape



from cape.maeeg import MAEEG_pl
model=MAEEG_pl()
test =next(iter(test_dataloader))
loss_reconstruction, preds, mask=model(test)
imgs = test["eeg"][:,None,...]
emb_enc, masks, ids_restore = model.forward_enc(imgs, 0.8)
preds = model.forward_dec(emb_enc, ids_restore)
loss_reconstruction = model.forward_loss(imgs, preds, masks)
import matplotlib.pyplot as plt

batch, preds, masks, patch_size, num_figures = (imgs,model.unpatchify(preds),masks,model.patch_size,3)

fig, axs = plt.subplots(num_figures, 3, figsize=(30, 15))
fig.tight_layout()
axs[0, 0].set_title("Ground-truth")
axs[0, 1].set_title("Masked Ground-truth")
axs[0, 2].set_title("Reconstruction")

for i, ax in enumerate(axs):

    sample = batch[i]
    pred, mask = preds[i], masks[i]


    pred = (pred).to("cpu").squeeze(0)[0].detach().numpy()
    sample = sample.to("cpu").squeeze(0)[0].numpy()
    sample_with_mask = (
        sample.reshape(-1,40)
    )
    mask = mask.to("cpu").numpy()

    # cor = np.corrcoef([pred, sample])[0, 1]

    x_axis = np.arange(0, sample.shape[-1])

    # groundtruth
    ax[0].plot(x_axis, sample)

    # groundtruth with mask
    s = 0
    for x, m in zip(sample_with_mask, mask[:40]):
        if m == 0:
            ax[1].plot(x_axis[s : s + len(x)], x, color="#1f77b4")
        s += len(x)
    
    
    # pred

    ax[2].plot(x_axis, pred)
    ax[2].set_ylabel("cor: %.4f" % 0, weight="bold")
    ax[2].yaxis.set_label_position("right")
    ax[0].set_xlim((-40,680))
    ax[1].set_xlim((-40,680))
    ax[2].set_xlim((-40,680))

fig_name = "reconst-%s" % (datetime.datetime.now().strftime("%d-%m-%Y-%H-%M"))

# plt.close(fig)




# AudioLDM2 Test

In [2]:
import torch
from huggingface_hub import hf_hub_download
checkpoint_path = hf_hub_download(
    repo_id="haoheliu/audioldm2-speech",
    
    filename="audioldm2-speech-gigaspeech.pth"
)

checkpoint = torch.load(checkpoint_path,map_location=torch.device('cpu'))

In [4]:
from autoEncoder import AutoencoderKL

first_stage_config= {
            "base_learning_rate": 0.000008,
            "target": "audioldm2.latent_encoder.autoencoder.AutoencoderKL",
            "params": {
                "sampling_rate": 16000,
                "batchsize": 4,
                "monitor": "val/rec_loss",
                "image_key": "fbank",
                "subband": 1,
                "embed_dim": 8,
                "time_shuffle": 1,
                "lossconfig": {
                    "target": "audioldm2.latent_diffusion.modules.losses.LPIPSWithDiscriminator",
                    "params": {
                        "disc_start": 50001,
                        "kl_weight": 1000,
                        "disc_weight": 0.5,
                        "disc_in_channels": 1,
                    },
                },
                "ddconfig": {
                    "double_z": True,
                    "mel_bins": 64,
                    "z_channels": 8,
                    "resolution": 256,
                    "downsample_time": False,
                    "in_channels": 1,
                    "out_ch": 1,
                    "ch": 128,
                    "ch_mult": [1, 2, 4],
                    "num_res_blocks": 2,
                    "attn_resolutions": [],
                    "dropout": 0,
                },
            },
        }

vae = AutoencoderKL(**first_stage_config['params'])


# model_dict =vae.state_dict()
# for key in model_dict.keys():
#     model_dict[key] = checkpoint['state_dict']['first_stage_model.'+key]

# vae.load_state_dict(model_dict)

In [6]:
pwd

'/mnt/nvme/node02/pranav/AE24'

In [7]:

from  chitVachana.openai_unet import UNetModel

unet_config= {
    "target": "audioldm2.latent_diffusion.modules.diffusionmodules.openaimodel.UNetModel",
    "params": {
        "image_size": 64,
        "context_dim": [768],
        "in_channels": 8,
        "out_channels": 8,
        "model_channels": 128,
        "attention_resolutions": [8, 4, 2],
        "num_res_blocks": 2,
        "channel_mult": [1, 2, 3, 5],
        "num_head_channels": 32,
        "use_spatial_transformer": True,
        "transformer_depth": 1,
    },
}
        
unet = UNetModel(**unet_config['params'])

model_dict =unet.state_dict()
for key in model_dict.keys():
    model_dict[key] = checkpoint['state_dict']['model.diffusion_model.'+key]

unet.load_state_dict(model_dict)



<All keys matched successfully>

In [15]:
from cape.maeeg import MAEEG,Encoder

b1=torch.randn((2,1,512,640))

lopo=Encoder()
abc=lopo(b1,0.8)
abc[0].shape

In [41]:

import sys
sys.path.insert(0, '/mnt/nvme/node02/pranav/AE24/chitVachana/cape')

In [1]:
%load_ext autoreload
%autoreload 2
from audioldm2.latent_diffusion.modules.encoders.modules import SequenceGenAudioMAECond   

import torch
from huggingface_hub import hf_hub_download
checkpoint_path = hf_hub_download(
    repo_id="haoheliu/audioldm2-speech",
    
    filename="audioldm2-speech-gigaspeech.pth"
)

checkpoint = torch.load(checkpoint_path,map_location=torch.device('cuda'))


seq_config=          {          "params": {
            "always_output_audiomae_gt": False,
            "learnable": False,
            "use_gt_mae_output": False,
            "use_gt_mae_prob": 1,
            "base_learning_rate": 0.0002,
            "sequence_gen_length": 512,
            "use_warmup": True,
            "sequence_input_key": [
              "crossattn_vits_phoneme"
            ],
            "sequence_input_embed_dim": [
              192
            ],
            "batchsize": 16,
            "cond_stage_config": {
              # "film_clap_cond1": {
              #   "cond_stage_key": "text",
              #   "conditioning_key": "film",
              #   "target": "audioldm2.latent_diffusion.modules.encoders.modules.CLAPAudioEmbeddingClassifierFreev2",
              #   "params": {
              #     "sampling_rate": 48000,
              #     "embed_mode": "text",
              #     "amodel": "HTSAT-base"
              #   }
              # },
              "crossattn_vits_phoneme": {
                "cond_stage_key": "phoneme_idx",
                "conditioning_key": "crossattn",
                "target": "audioldm2.latent_diffusion.modules.encoders.modules.PhonemeEncoder",
                "params": {
                  "vocabs_size": 183,
                  "pad_token_id": 0,
                  "pad_length": 310
                }
              },
              "crossattn_audiomae_pooled": {
                "cond_stage_key": "ta_kaldi_fbank",
                "conditioning_key": "crossattn",
                "target": "audioldm2.latent_diffusion.modules.encoders.modules.AudioMAEConditionCTPoolRand",
                "params": {
                  "regularization": False,
                  "no_audiomae_mask": True,
                  "time_pooling_factors": [
                    1
                  ],
                  "freq_pooling_factors": [
                    1
                  ],
                  "eval_time_pooling": 1,
                  "eval_freq_pooling": 1,
                  "mask_ratio": 0
                }
              }
            }
          }}


seq_model = SequenceGenAudioMAECond(**seq_config["params"])

model_dict =seq_model.state_dict()
for key in model_dict.keys():
    okey=key
    if "cond_stage_models.0." in key:
      okey=key.replace("cond_stage_models.0.","cond_stage_models.1.")
    else:
      okey=key.replace("cond_stage_models.1.","cond_stage_models.2.")
    
    if "input_sequence_embed_linear.0." in key:
      okey=okey.replace("input_sequence_embed_linear.0.","input_sequence_embed_linear.1.")
    else:
      okey=okey.replace("input_sequence_embed_linear.1.","input_sequence_embed_linear.2.")
    
    model_dict[key] = checkpoint['state_dict']['cond_stage_models.0.'+okey]

seq_model.load_state_dict(model_dict)
# seq_model.half()
audiomae=seq_model.cond_stage_models[1]

del checkpoint

In [ ]:


# from torch.utils.data import DataLoader


# eeg_config= {'preprocessing':{'audio': {'sampling_rate': 16000,
#   'max_wav_value': 32768.0,
#   'duration': 10,
#   'hop_length': 4},
#  'stft': {'filter_length': 1024, 'hop_length': 160, 'win_length': 1024},
#  'mel': {'n_mel_channels': 64, 'mel_fmin': 0, 'mel_fmax': 8000}},
 
# #  'data':{'train': ['stimuli'],
# #  'val': 'stimuli',
# #  'test': 'stimuli',
# #  'class_label_indices': 'audioset_eval_subset',
# #  'dataloader_add_ons': []},
# #  'augmentation':{'mixup':""}
#  }



# from audioldm_train.utilities.data.eeg_dataset import EEGDataset
# tdataset = EEGDataset(eeg_config,split="train")
# vdataset = EEGDataset(eeg_config,split="val")
# tdataset = EEGDataset(eeg_config,split="test")

# loader = DataLoader(
#     tdataset,
#     batch_size=120,
#     num_workers=2,
#     pin_memory=True,
#     persistent_workers =True,
#     shuffle=False,

# )



In [3]:
import numpy as np
from tqdm import tqdm
from audioldm_train.utilities.data.eeg_dataset import EEGDataset
from torch.utils.data import DataLoader


eeg_config= {'preprocessing':{'audio': {'sampling_rate': 16000,
  'max_wav_value': 32768.0,
  'duration': 10,
  'hop_length': 4},
 'stft': {'filter_length': 1024, 'hop_length': 160, 'win_length': 1024},
 'mel': {'n_mel_channels': 64, 'mel_fmin': 0, 'mel_fmax': 8000}},
}

def createNPY(split,bs=256,nw=4):
    dataset = EEGDataset(eeg_config,split=split)

    loader = DataLoader(
        dataset,
        batch_size=bs,
        num_workers=nw,
        shuffle=False,

    )

    filename = f"/mnt/nvme/node02/pranav/AE24/data/pytorch_save/{split}_audiomae.npy"
    fp = np.memmap(filename, dtype='float32', mode='w+', shape=(len(dataset),512, 768))
    audiomae.eval()
    audiomae.to('cuda')
    with torch.inference_mode():
        for i,samp in enumerate(tqdm(loader)):
            inp =samp["ta_kaldi_fbank"].cuda()
            fp[samp["index"]]= audiomae(inp)[0].detach().cpu().numpy()

    fp.flush()

In [11]:

split= "test"
bs=60
nw=4


dataset = EEGDataset(eeg_config,split=split)

loader = DataLoader(
    dataset,
    batch_size=bs,
    num_workers=nw,
    shuffle=False,

)

In [12]:
sample=(next(iter(loader)))

In [13]:


filename = f"/mnt/nvme/node02/pranav/AE24/data/pytorch_save/{split}_audiomae.npy"
fp = np.lib.format.open_memmap(filename, dtype='float32', mode='w+', shape=(len(dataset),512, 768))
audiomae.eval()
audiomae.to('cuda')

for i,samp in enumerate(tqdm(loader)):
    inp =samp["ta_kaldi_fbank"].cuda()
    with torch.inference_mode():
        fp[samp["index"]]= audiomae(inp)[0].detach().cpu().numpy()

fp.flush()

100%|████████████████████████████████████████████████████████████| 216/216 [13:45<00:00,  3.82s/it]


In [3]:
import torch
filename = f"/mnt/nvme/node02/pranav/AE24/data/pytorch_save/testing.npy"
fp = np.lib.format.open_memmap(filename, dtype='float32', mode='w+', shape=(112800,512, 768))

for i,samp in enumerate(tqdm(range(200))):
    inp =torch.ones((512,768))*i
    fp[i,:,:]= inp.detach().cpu().numpy()

fp.flush()

100%|██████████| 200/200 [00:00<00:00, 261.21it/s]


In [6]:
import numpy as np
aud_path = f"/mnt/nvme/node02/pranav/AE24/data/pytorch_save/testing.npy"
audlat = np.load(aud_path,mmap_mode="r+")[[1,3,2211]]
audlat.shape


(3, 512, 768)

In [1]:
import numpy as np

In [1]:
%load_ext autoreload
%autoreload 2


from tqdm import tqdm
from audioldm_train.utilities.data.eeg_dataset import EEGDataset
from torch.utils.data import DataLoader, default_collate
import torch
import numpy as np

eeg_config= {'preprocessing':{'audio': {'sampling_rate': 16000,
  'max_wav_value': 32768.0,
  'duration': 10,
  'hop_length': 4},
 'stft': {'filter_length': 1024, 'hop_length': 160, 'win_length': 1024},
 'mel': {'n_mel_channels': 64, 'mel_fmin': 0, 'mel_fmax': 8000}},
}

# split="train"
# audiolatents = np.memmap(
# f"/mnt/nvme/node02/pranav/AE24/data/pytorch_save/{split}_audiomae.npz",
# dtype="float32",
# mode="r",
# shape=(112800, 512, 768),
# )

def collate(batch):
    aud_path = f"/mnt/nvme/node02/pranav/AE24/data/pytorch_save/train_audiomae.npy"
    batch=default_collate(batch)
    batch['audio_latent']=torch.from_numpy(np.load(aud_path,mmap_mode="r")[batch['index']].copy()).type(torch.float32)

    return batch


dataset = EEGDataset(eeg_config,split="train")

loader = DataLoader(
    dataset,
    batch_size=120,
    num_workers=8,
    pin_memory=True,
    persistent_workers =False,
    shuffle=False,
    collate_fn=collate,

)
# 10.33m 120bs 4w eeg pwT
# 10.33m per 113/221 512bs 4w eeg pwT
# 14m 60bs 2w eeg pwT

# 55s 512bs 2w eeg pwF
# 29s 120bs 4w eeg pwF (1m if memap)
# 29s 60bs 4w eeg pwF

# 12m 60bs 4w eeg+aud pwF
# 16m 120bs 4w eeg+aud collate
# 25m 120bs 4w eeg+aud no collate

#np.load with dummy
# 3.40m 120bs 4w eeg+aud no collate
# 4.34m 120bs 4w eeg+aud  collate

#np.load with real
# 15.42m 120bs 4w eeg+aud no collate
# 16.11m 120bs 4w eeg+aud  collate

# 13.23m 120bs 8w eeg+aud  collate

for batch in tqdm(loader):
    op=0
    


100%|██████████| 940/940 [13:23<00:00,  1.17it/s]


In [5]:
from tqdm import tqdm
aud_path = f"/mnt/nvme/node02/pranav/AE24/data/pytorch_save/val_audiomae.npy"
z= np.load(aud_path,mmap_mode="r")
for i in tqdm(range(len(z))):
    KILO=z[i]
    np.save(f"/mnt/nvme/node02/pranav/AE24/data/audiomae/val/amae_{i}.npy",KILO)

#10m.53

100%|██████████| 12902/12902 [03:31<00:00, 61.02it/s] 


In [2]:
import torch
import numpy as np
ki =np.load("/mnt/nvme/node02/pranav/AE24/data/audiomae/train/amae_112715.npy")


In [12]:
sample= next(iter(loader))
print(sample.keys(),len(dataset))

dict_keys(['index', 'eeg']) 12902


In [4]:
sample["eeg"].shape


torch.Size([512, 64, 640])

In [1]:
from transformers import GPT2Config, GPT2Model
from transformers.models.gpt2.modeling_gpt2 import GPT2Block

# Initializing a GPT2 configuration
configuration = GPT2Config()

# Initializing a model (with random weights) from the configuration
model = GPT2Block(configuration,0)



In [13]:
import torch
oup=model(torch.ones(3,2,768))

In [15]:
len(oup),oup[0].shape,oup

(1,
 torch.Size([3, 2, 768]),
 (tensor([[[1., 1., 1.,  ..., 1., 1., 1.],
           [1., 1., 1.,  ..., 1., 1., 1.]],
  
          [[1., 1., 1.,  ..., 1., 1., 1.],
           [1., 1., 1.,  ..., 1., 1., 1.]],
  
          [[1., 1., 1.,  ..., 1., 1., 1.],
           [1., 1., 1.,  ..., 1., 1., 1.]]], grad_fn=<AddBackward0>),))

In [3]:
from torchinfo import summary
summary(model,input_size= (60,512,768))


Layer (type:depth-idx)                   Output Shape              Param #
GPT2Block                                [60, 512, 768]            --
├─LayerNorm: 1-1                         [60, 512, 768]            1,536
├─GPT2Attention: 1-2                     [60, 512, 768]            --
│    └─Conv1D: 2-1                       [60, 512, 2304]           1,771,776
│    └─Dropout: 2-2                      [60, 12, 512, 512]        --
│    └─Conv1D: 2-3                       [60, 512, 768]            590,592
│    └─Dropout: 2-4                      [60, 512, 768]            --
├─LayerNorm: 1-3                         [60, 512, 768]            1,536
├─GPT2MLP: 1-4                           [60, 512, 768]            --
│    └─Conv1D: 2-5                       [60, 512, 3072]           2,362,368
│    └─NewGELUActivation: 2-6            [60, 512, 3072]           --
│    └─Conv1D: 2-7                       [60, 512, 768]            2,360,064
│    └─Dropout: 2-8                      [60, 512, 76

In [1]:
import sys
sys.path.insert(0,"/mnt/nvme/node02/pranav/AE24/chitVachana/cape")

In [3]:
from cape.align import alignEEG
from torchinfo import summary
maybe=alignEEG()
summary(maybe)

Layer (type:depth-idx)                        Param #
alignEEG                                      --
├─eeg2latent: 1-1                             --
│    └─Encoder: 2-1                           394,752
│    │    └─Patch2DEmbed: 3-1                 (62,208)
│    │    └─ModuleList: 3-2                   (70,878,720)
│    │    └─LayerNorm: 3-3                    (1,536)
│    └─GPT2Block: 2-2                         --
│    │    └─LayerNorm: 3-4                    1,536
│    │    └─GPT2Attention: 3-5                2,362,368
│    │    └─LayerNorm: 3-6                    1,536
│    │    └─GPT2MLP: 3-7                      4,722,432
├─InfoNCE: 1-2                                --
Total params: 78,425,088
Trainable params: 7,087,872
Non-trainable params: 71,337,216

In [32]:
import torch
torch.save(torch.arange(1128*512*768).reshape(1128,512,768),"test.pt")


  0%|                                                                                | 0/26 [00:00<?, ?it/s]

100%|████████████████████████████████████████████████████████████████████| 26/26 [1:32:18<00:00, 213.02s/it]


In [18]:
import numpy as np
fpath= "/mnt/nvme/node02/pranav/AE24/data/pytorch_save/val.npz"
fp =np.memmap(fpath, dtype='float32',mode='r',shape=(112800,512, 768))
import torch

In [8]:
idx=torch.arange(100)

In [21]:
ki=np.load(fpath,mmap_mode="r")[0]

ValueError: Cannot load file containing pickled data when allow_pickle=False

In [17]:
for k in range(512):
    # idx*=k+20
    torch.from_numpy(fp[k].copy()).type(torch.float32).shape


#512=43s

In [ ]:
filename = "/mnt/nvme/node02/pranav/AE24/data/pytorch_save/phoneme.npz"
fp = np.memmap(filename, dtype='float32', mode='w+', shape=(112800,512, 768))

for i,samp in enumerate(tqdm(loader)):
    inp =samp["ta_kaldi_fbank"].cuda()
    fp[samp["index"]]=audiomae(inp)[0].to('cpu')

In [31]:
!du -sh /storage/pranav//node02/data/pytorch_save/test.npz

12M	/storage/pranav//node02/data/pytorch_save/test.npz


In [12]:
#srun --nodes 1 --ntasks-per-node=2 -p node03 --gres=gpu:2 --pty python /mnt/nvme/node02/pranav/AE24/chitVachana/cape/align.py    
sample= next(iter(loader))
print(sample.keys())
# print(sample['phoneme_idx'].shape)
#100 =>42s only takaldi

# for k,v in sample.items():
#     if isinstance(v, torch.Tensor):# and v.dtype == torch.float32:
#         sample[k]=v.to('cuda')


dict_keys(['index', 'fname', 'ta_kaldi_fbank', 'duration', 'sampling_rate', 'text', 'phoneme_idx'])


In [15]:
seq_model.eval()
seq_model.to('cuda')
with torch.inference_mode():
    t2=seq_model(sample)

# half()
#160 in 8min
#100 in 4min
#80 in 4 min 
    
#full
#100 in 11min

In [16]:
t2

{'crossattn_audiomae_generated': [tensor([[[-1.4411, -0.2817,  0.8758,  ...,  0.2904, -0.8685, -0.7751],
           [-1.5329, -0.4374,  0.6913,  ...,  0.3614, -1.0018, -0.8935],
           [-1.3803, -0.2971,  0.2925,  ...,  0.2381, -0.8082, -0.9161],
           ...,
           [-0.9763,  0.1727,  0.1323,  ..., -0.1783, -0.0093,  0.2163],
           [-1.0156,  0.2128,  0.4268,  ..., -0.2187, -0.0923,  0.2174],
           [-1.0247, -0.0808,  0.4300,  ..., -0.2984,  0.0104,  0.2565]],
  
          [[-1.4473, -0.2979,  0.8868,  ...,  0.2985, -0.8991, -0.7798],
           [-1.5182, -0.4360,  0.6736,  ...,  0.3601, -1.0161, -0.8936],
           [-1.2701, -0.2782,  0.2452,  ...,  0.2082, -0.7801, -0.8802],
           ...,
           [-0.9588,  0.2886,  0.0826,  ..., -0.2159, -0.0847,  0.3511],
           [-0.9959,  0.3611,  0.3616,  ..., -0.2253, -0.1862,  0.3481],
           [-0.9910,  0.1074,  0.3489,  ..., -0.2896, -0.0932,  0.3768]],
  
          [[-1.4287, -0.2817,  0.8711,  ...,  0.2829

In [24]:
from torchsummary import summary
summary(seq_model,input_size=)


AttributeError: 'Tensor' object has no attribute 'keys'

In [10]:
t2['crossattn_audiomae_generated'][0].shape,t2['crossattn_vits_phoneme'][0].shape

(torch.Size([1, 512, 768]), torch.Size([1, 310, 192]))

In [68]:
value=t2['crossattn_audiomae_pooled'][0]==t1[0]

In [1]:
import torch.nn as nn
import torch
conv = nn.Conv1d(100,100,10).to('cuda')

q=torch.ones((100,100)).to('cuda')
k=torch.ones((100,100)).to('cuda')
conv(q)


tensor([[ 1.0192,  1.0192,  1.0192,  ...,  1.0192,  1.0192,  1.0192],
        [ 0.2569,  0.2569,  0.2569,  ...,  0.2569,  0.2569,  0.2569],
        [ 0.5614,  0.5614,  0.5614,  ...,  0.5614,  0.5614,  0.5614],
        ...,
        [ 0.9996,  0.9996,  0.9996,  ...,  0.9996,  0.9996,  0.9996],
        [-0.1738, -0.1738, -0.1738,  ..., -0.1738, -0.1738, -0.1738],
        [-1.3580, -1.3580, -1.3580,  ..., -1.3580, -1.3580, -1.3580]],
       device='cuda:0', grad_fn=<SqueezeBackward1>)

In [4]:
dir(torch.backends.cudnn)

['__doc__', '__loader__', '__name__', '__package__', '__spec__', 'm']

In [4]:
torch.version()

TypeError: 'module' object is not callable

In [2]:
import torch
print(torch.cuda.is_available())
print(torch.cuda.device_count())
print(torch.backends.cudnn.enabled)
print(torch.backends.cudnn.version())


True
1
True
8700


In [10]:
import os
print(os.environ['LD_LIBRARY_PATH'])
#print(os.environ['CUDA_HOME'])
os.environ['LD_LIBRARY_PATH'] = '/mnt/nvme/node02/pranav/AE24/cudnn-linux-x86_64-8.7.0.84_cuda11-archive/lib' #+ os.environ.get('LD_LIBRARY_PATH', '')
os.environ['CUDA_HOME'] = os.environ.get('CONDA_PREFIX', '')

# Verify the change
print(os.environ['LD_LIBRARY_PATH'])
print(os.environ['CUDA_HOME'])


/mnt/nvme/node02/pranav/AE24/cudnn-linux-x86_64-8.7.0.84_cuda11-archive/lib
/home/pranav/miniconda3/envs/ae24_pt


In [13]:
!echo $PATH

/home/pranav/miniconda3/envs/ae24_pt/bin:/usr/local/cuda/bin:/usr/local/bin:/usr/local/sbin:/home/pranav/miniconda3/envs/ae24/bin:/mnt/server-home/pranav/.vscode-server/bin/8b3775030ed1a69b13e4f4c628c612102e30a681/bin/remote-cli:/home/pranav/.local/bin:/home/pranav/miniconda3/condabin:/usr/local/cuda/bin:/usr/local/bin:/usr/local/sbin:/home/pranav/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/local/tensorrt/bin:/usr/local/tensorrt/bin


In [36]:
nugumbu.keys()
audiomae_emb =  nugumbu['crossattn_audiomae_pooled'][0].reshape((3,-1))
phoneme_emb = nugumbu['crossattn_audiomae_generated'][0].reshape((3,-1))
audiomae_emb@phoneme_emb.T/(audiomae_emb@phoneme_emb.T).sum()

tensor([[0.1112, 0.1113, 0.1100],
        [0.1124, 0.1113, 0.1089],
        [0.1102, 0.1111, 0.1135]], device='cuda:0')

In [42]:
aemb=torch.nn.functional.normalize(audiomae_emb, dim=1, p = 2)
pemb=torch.nn.functional.normalize(phoneme_emb, dim=1, p = 2)
aemb.shape

torch.Size([3, 393216])

In [47]:
aemb.max(),pemb.max()

(tensor(0.0154, device='cuda:0'), tensor(0.0160, device='cuda:0'))

In [51]:
cs = torch.nn.CosineSimilarity(dim=1, eps=1e-08)
cs(aemb[0:1],pemb[0:1])

tensor([0.7733], device='cuda:0')

In [7]:
from phonemizer.backend import EspeakBackend
from phonemizer.separator import Separator
from phonemizer import phonemize
from phonemizer.logger import get_logger
from phonemizer.backend.espeak.wrapper import EspeakWrapper

EspeakWrapper.set_library('/mnt/nvme/node02/pranav/AE24/AudioLDM-training-finetuning/AudioLDM2/espeak/bin/espeak-ng')
backend = EspeakBackend("nl")
separator = Separator(phone=None, word=" ", syllable="|")

from tqdm import tqdm
phones =[]
for k,v in tqdm(dataset.index_map.items()):

    raw_phones = backend.phonemize(
    [v[3]],
    strip=True,
    )
    dataset.index_map[k]=v+(raw_phones[0],)
    # print(raw_phones)


from audioldm2.pipeline import *
for k in range(1000):
    ids = get_vits_phoneme_ids_no_padding([text2phoneme(["unload of the "], lng="nl")])


  0%|                                                                                                                                         | 0/112716 [00:00<?, ?it/s]

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 112716/112716 [00:37<00:00, 3024.71it/s]


TypeError: expected string or bytes-like object

In [9]:
text2phoneme("unload of the ", lng="nl")

'ˈɵnloːˌɑt ɔf ðə'

In [65]:
from cape.maeeg import Encoder 
from torch import nn



default ={        
        "img_size":(64, 640),  # eeg x time (10s)
        "in_chans":1,
        "patch_size":(8, 10),
        "enc_embed_dim":768,
        "enc_depth":10,
        "enc_num_heads":12,
        "mlp_ratio":4,
        "norm_layer":nn.LayerNorm,
        "pos_trainable":False,
        "pos_dim":1,
        "mask_ratio":0.8,
        
        }

class ProjectionHead(nn.Module):
    def __init__(
        self,
        embedding_dim,
        projection_dim,
        dropout
    ):
        super().__init__()
        self.projection = nn.Linear(embedding_dim, projection_dim)
        self.gelu = nn.GELU()
        self.fc = nn.Linear(projection_dim, projection_dim)
        self.dropout = nn.Dropout(dropout)
        self.layer_norm = nn.LayerNorm(projection_dim)
    
    def forward(self, x):
        projected = self.projection(x)
        x = self.gelu(projected)
        x = self.fc(x)
        x = self.dropout(x)
        x = x + projected
        x = self.layer_norm(x)
        return x
    

class eeg2latent(nn.Module):
    def __init__(self,config=default,device="cpu"):
        super().__init__()
        ckpt ="/mnt/nvme/node02/pranav/AE24/chitVachana/cape/checkpoint/maeeg_512_enc768_dec256_29-03-2024-02-17.ckpt"
        state_dict=torch.load(ckpt,map_location=device)

        self.encoder=Encoder(**config)
        self.encoder.load_state_dict(state_dict,strict=False)
        self.dim = config["enc_embed_dim"]
        self.projection =ProjectionHead(self.dim,self.dim,0.5)

    def forward(self, x):
        # B,  64, 640 -> B, 512, 786
        x= self.encoder(x)
        # B, 512, 786 -> B, 512, 786
        x=self.projection(x)
        return x




In [96]:
from cape.config import Config_MBM_EEG, config_dict

el=eeg2latent(config_dict['maeeg_config']['params'])


In [68]:
sample['eeg'].shape

torch.Size([3, 512, 64])

In [49]:
from IPython.display import Audio

Audio(sample['waveform'][1].squeeze(), rate=16000)

In [78]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [99]:
x=torch.zeros((2,3,4))
torch.permute(x,(0,2,1)).shape

torch.Size([2, 4, 3])

In [161]:
from audioldm2.pipeline import *

phonemes=[]
for sam_text in sample['text']:
    phonemes.append(text2phoneme(sam_text,lng="nl"))



ids=get_vits_phoneme_ids_no_padding(phonemes)
sample.update(ids)
print(len(phonemes),ids['phoneme_idx'].shape)

waveform = torch.FloatTensor(sample['waveform'])
assert waveform.size(0) == 3
ta_kaldi_fbank =extract_kaldi_fbank_feature(waveform.squeeze(), 16000, sample['log_mel_spec'])

sample.update(ta_kaldi_fbank)

3 torch.Size([3, 310])


In [28]:
audiomae=seq_model.cond_stage_models[2]

In [29]:
sample['ta_kaldi_fbank']

tensor([[[-0.4938, -0.5961, -0.2192,  ..., -0.7529, -0.5389, -0.4309],
         [-0.6635, -0.7921, -0.4153,  ..., -0.4778, -0.5167, -0.3655],
         [-0.4769, -0.6787, -0.3018,  ..., -0.5573, -0.4668, -0.4567],
         ...,
         [ 0.4670,  0.4670,  0.4670,  ...,  0.4670,  0.4670,  0.4670],
         [ 0.4670,  0.4670,  0.4670,  ...,  0.4670,  0.4670,  0.4670],
         [ 0.4670,  0.4670,  0.4670,  ...,  0.4670,  0.4670,  0.4670]],

        [[-0.4249, -0.1686,  0.2083,  ...,  0.3558,  0.2334,  0.2759],
         [-0.4655, -0.1772,  0.1997,  ...,  0.3328,  0.2030,  0.2830],
         [-0.3704, -0.1786,  0.1982,  ...,  0.3160,  0.2076,  0.3603],
         ...,
         [ 0.4670,  0.4670,  0.4670,  ...,  0.4670,  0.4670,  0.4670],
         [ 0.4670,  0.4670,  0.4670,  ...,  0.4670,  0.4670,  0.4670],
         [ 0.4670,  0.4670,  0.4670,  ...,  0.4670,  0.4670,  0.4670]],

        [[-1.0832, -1.2776, -1.0034,  ..., -0.7623, -0.8262, -1.0491],
         [-1.1560, -1.2776, -1.2406,  ..., -0

In [30]:
inp=sample['ta_kaldi_fbank']
print(inp.shape)
a,b=audiomae(inp)
print(a.shape,b.shape)

torch.Size([3, 1024, 128])
torch.Size([3, 512, 768]) torch.Size([3, 512])


In [36]:
a[0]

tensor([[-0.9501,  0.3998,  0.6282,  ..., -0.0220, -0.3088, -0.0524],
        [-0.0740,  0.3107,  0.1126,  ...,  0.3598, -0.2239, -0.5336],
        [ 0.0618, -0.1331,  0.0373,  ..., -0.1004, -0.2331, -0.0950],
        ...,
        [-0.7071,  0.4925, -0.5344,  ...,  0.1503, -0.1899, -0.0133],
        [-0.4885,  0.4764, -0.4817,  ...,  0.1010, -0.3364, -0.1222],
        [-0.2424,  0.3204, -0.4070,  ...,  0.2397, -0.2224, -0.1475]],
       device='cuda:0')

In [45]:
nugumbu['crossattn_audiomae_generated'][0][1]==a[1]

tensor([[False, False, False,  ..., False, False, False],
        [False, False, False,  ..., False, False, False],
        [False, False, False,  ..., False, False, False],
        ...,
        [False, False, False,  ..., False, False, False],
        [False, False, False,  ..., False, False, False],
        [False, False, False,  ..., False, False, False]], device='cuda:0')

In [46]:
print(nugumbu.keys())
print(nugumbu['crossattn_audiomae_pooled'][0].shape)#from audiomae
print(nugumbu['crossattn_audiomae_generated'] [0].shape)#from phonemes
print(nugumbu['crossattn_vits_phoneme'] [0].shape)

dict_keys(['crossattn_audiomae_generated', 'film_clap_cond1', 'crossattn_vits_phoneme', 'crossattn_audiomae_pooled'])
torch.Size([3, 512, 768])
torch.Size([3, 512, 768])
torch.Size([3, 310, 192])


In [27]:
from audioldm2.pipeline import *
#ldm = build_model(model_name="audioldm2-speech-gigaspeech",device='cuda')
wtf=make_batch_for_text_to_audio("","amazing")

In [41]:
wtf['ta_kaldi_fbank'].shape

torch.Size([1, 1024, 128])

In [38]:
ldm.latent_t_size = int(5*25.6)

with torch.no_grad():
    waveform = ldm.generate_batch(
        wtf,
        unconditional_guidance_scale=3.5,
        ddim_steps=10,
        n_gen=3,
        duration=5,
    )

batch************: dict_keys(['text', 'fname', 'waveform', 'stft', 'log_mel_spec', 'ta_kaldi_fbank', 'phoneme_idx'])
cond_keys***********************************: fbank 2 dict_keys(['crossattn_audiomae_generated'])
Running DDIM Sampling with 10 timesteps


DDIM Sampler: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 10/10 [00:12<00:00,  1.28s/it]


INFO: clap model calculate the audio embedding as condition
Similarity between generated audio and text:
0.16 0.19 0.19
Choose the following indexes as the output: [2]


In [43]:
from IPython.display import Audio

Audio(waveform.squeeze(), rate=16000)


In [3]:
seq_model.to('cuda')
for k in wtf.keys():
    if isinstance(wtf[k],torch.Tensor):
        print(k)
        wtf[k]=wtf[k].to('cuda')

with torch.no_grad():
    nugumbu=seq_model(wtf)

waveform
stft
log_mel_spec
ta_kaldi_fbank
phoneme_idx
sequence gen in ................. {'text': [''], 'fname': [''], 'waveform': tensor([[0., 0., 0.,  ..., 0., 0., 0.]], device='cuda:0'), 'stft': tensor([[[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]]], device='cuda:0'), 'log_mel_spec': tensor([[[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]]], device='cuda:0'), 'ta_kaldi_fbank': tensor([[[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0.,

In [6]:
nugumbu.keys()

dict_keys(['crossattn_audiomae_generated', 'film_clap_cond1', 'crossattn_vits_phoneme', 'crossattn_audiomae_pooled'])

In [12]:
(nugumbu['crossattn_audiomae_generated'][0].shape,
nugumbu['crossattn_vits_phoneme'][0].shape, nugumbu['crossattn_audiomae_pooled'][0].shape)

(torch.Size([1, 512, 768]),
 torch.Size([1, 310, 192]),
 torch.Size([1, 512, 768]))

In [ ]:
512,768 => TIME,DIM

In [12]:
from numba import cuda
cuda.select_device(0)
cuda.close() 

ERROR:numba.cuda.cudadrv.driver:Call to cuMemGetInfo results in UNKNOWN_CUDA_ERROR


CudaAPIError: [700] Call to cuMemGetInfo results in UNKNOWN_CUDA_ERROR

In [8]:
import torch
torch.cuda.empty_cache()

!nvidia-smi

Sun Mar 24 15:53:38 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.86.10              Driver Version: 535.86.10    CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla V100-SXM2-32GB           On  | 00000000:1A:00.0 Off |                    0 |
| N/A   32C    P0              55W / 300W |  11857MiB / 32768MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [ ]:
checkpoint['state_dict'].keys()

In [3]:
#espeak test
from phonemizer import phonemize
phonemes = phonemize("kill me", language='en-us', backend='espeak', strip=True, preserve_punctuation=True, with_stress=True)

# DDPM

In [1]:
%load_ext autoreload
%autoreload 2


In [31]:
import os
import yaml

from audioldm_train.utilities.model_util import instantiate_from_config
from torch.utils.data import Subset,DataLoader
config_yaml = "/mnt/nvme/node02/pranav/AE24/AudioLDM-training-finetuning/audioldm_train/config/2023_08_23_reproduce_audioldm/audioldm_eeg.yaml"


config_yaml_path = os.path.join(config_yaml)
configs = yaml.load(open(config_yaml_path, "r"), Loader=yaml.FullLoader)


from audioldm_train.utilities.data.eeg_dataset import EEGDataset
val_dataset = EEGDataset(configs, split="test")
valsub= Subset(val_dataset,range(16))
val_loader = DataLoader(
    valsub,
    batch_size=1,
)

val_samp= next(iter(val_loader))


/mnt/nvme/node02/pranav/AE24/AudioLDM-training-finetuning/audioldm_train/utilities/audio/stft.py:42: FutureWarning: Pass size=1024 as keyword args. From version 0.10 passing these as positional arguments will result in an error
  fft_window = pad_center(fft_window, filter_length)
/mnt/nvme/node02/pranav/AE24/AudioLDM-training-finetuning/audioldm_train/utilities/audio/stft.py:145: FutureWarning: Pass sr=16000, n_fft=1024, n_mels=64, fmin=0, fmax=8000 as keyword args. From version 0.10 passing these as positional arguments will result in an error
  mel_basis = librosa_mel_fn(
/mnt/nvme/node02/pranav/AE24/AudioLDM-training-finetuning/audioldm_train/utilities/data/eeg_dataset.py:248: FutureWarning: Pass sr=16000, n_fft=1024, n_mels=64, fmin=0, fmax=8000 as keyword args. From version 0.10 passing these as positional arguments will result in an error
  mel = librosa_mel_fn(


In [34]:
val_samp.keys()

dict_keys(['fname', 'eeg', 'mel', 'waveform', 'stft', 'log_mel_spec', 'duration', 'sampling_rate', 'text', 'label_vector', 'random_start_sample_in_original_audio_file'])

In [39]:
val_samp['eeg'].shape,val_samp['mel'].shape,val_samp['log_mel_spec'].shape,val_samp['stft'].shape,

(torch.Size([1, 512, 64]),
 torch.Size([1, 512, 10]),
 torch.Size([1, 800, 64]),
 torch.Size([1, 800, 512]))

In [47]:
768*512,1024*128,640*64

(393216, 131072, 40960)

In [51]:
1024*128/(16*16),64*8

(512.0, 512)

In [55]:
640*64/(10*8)

512.0

In [4]:
import torch
qa=torch.utils.data.DataLoader(dataset,batch_size=2)
sample = next(iter(qa))

NameError: name 'dataset' is not defined

In [34]:
from ddpm import LatentDiffusion
ldm= LatentDiffusion()



/home/pranav/miniconda3/envs/ae24/lib/python3.10/site-packages/pl_bolts/models/self_supervised/amdim/amdim_module.py:34: UnderReviewWarning: The feature generate_power_seq is currently marked under review. The compatibility with other Lightning projects is not guaranteed and API may change at any time. The API and functionality may change without warning in future releases. More details: https://lightning-bolts.readthedocs.io/en/latest/stability.html
  "lr_options": generate_power_seq(LEARNING_RATE_CIFAR, 11),
/home/pranav/miniconda3/envs/ae24/lib/python3.10/site-packages/pl_bolts/models/self_supervised/amdim/amdim_module.py:92: UnderReviewWarning: The feature FeatureMapContrastiveTask is currently marked under review. The compatibility with other Lightning projects is not guaranteed and API may change at any time. The API and functionality may change without warning in future releases. More details: https://lightning-bolts.readthedocs.io/en/latest/stability.html
  contrastive_task: Un

+ Use extra condition on UNet channel using Film. Extra condition dimension is 512. 


In [ ]:
ldm.generate_sample(val_samp)

100%|██████████| 10/10 [00:06<00:00,  1.47it/s]


melshape: torch.Size([1, 1, 1024, 64])


array([[[0.01618918, 0.00900588, 0.01666717, ..., 0.01344001,
         0.01058442, 0.00704314]]], dtype=float32)

In [ ]:
mar 14

- RuntimeError: mat1 and mat2 shapes cannot be multiplied (2048x256 and 512x256) #concat context?
- why mismatch: timesteps_dim effects 2048
- chnage something to make both same Value


16.0

In [24]:
32*32
/mnt/nvme/node02/pranav/AE24/AudioLDM-training-finetuning/AudioLDM2/test.ipynb

1024

In [35]:
import torch
line=torch.nn.Linear(12,23)

inp = torch.randn(2,5,77, 12)

oup=line(inp)
oup.shape

torch.Size([2, 5, 77, 23])

In [25]:
327680/1024

320.0